name: Adsterra Auto Clicker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'  # रोज सुबह 9:30AM IST (4AM UTC)

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run click script
        run: |
          python main.py
          
