name: Adsterra Auto Clicker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'  # Runs daily at 9:30 AM IST

jobs:
  click_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run main script
        run: |
          python main.py
          
